version: '3.8'

services:
  gellyte:
    build: .
    container_name: gellyte-server
    environment:
      - GIN_MODE=release
    ports:
      - "8080:8080"
    volumes:
      # Base de datos persistente
      - ./gellyte.db:/root/gellyte.db
      # Tus películas (mapea tu carpeta real aquí si prefieres)
      - ./media/peliculas:/root/media/peliculas
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
